TELEBOT:
  TOKEN:               # e.g., 1234567890:hellohowareyouiamfine
  ADMIN_CHATID:        # e.g., 1234567890
DB:
  HOST:                # e.g., 192.168.0.1, localhost
  PORT:                # MySQL port, default is 3306
  USER:                # Your ID
  PASSWD:              # Your password
  NAME:                # Name of database
IPC:
  PORT:                # rpyc port

